Update CFDataset to understand CMIP6 metadata format
pacificclimate/nchelpers pull request #87
Opened 2021-08-06 00:12 UTC by corviday

CMIP6 has renamed several of the required attributes since CMIP5. This PR adds the new attribute names that are updates of existing attribute names to nchelper`, along with a CMIP6 test case. 

A list of the renamed attributes can be seen [here](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk), but most of them aren't used by nchelpers and so didn't need to be updated. I plan to also write a Confluence document listing all attributes we expect in a CMIP6 document - the official CMIP6 attributes, plus the additional PCIC ones we used with CMIP5 files.

2021-08-06 19:05 UTC, rod-glover requested changes
I think one (or both!) of us may have a misunderstanding of how the aliases work. See comments on the alias dicts. Let's discuss.

We also need some tests of the aliases against one or more CMIP6 files in `tests/test_CFDataset.py::test_metadata_simple_property`. And, depending on what decision we make about putting in new aliases for CMIP5, some new ones there too.

2021-08-06 19:23 UTC, corviday commented on nchelpers/__init__.py
> +                        self.metadata.project not in ('IPCC Fourth Assessment', 'CMIP5', 'CMIP6'):
This whole file could use a blackify, but I was planning to do it as a separate PR.

2021-08-06 19:25 UTC, corviday commented on tests/test_CFDataset.py
> +     'pr_day_BCCAQv2_MPI-ESM1-2-HR_historical-ssp126_r1i1p1f1_19500101-19500131_Canada'),
I'll rename it `tiny_cmip6_gcm.nc`.

2021-08-06 19:31 UTC, corviday commented on nchelpers/__init__.py
> +                'realm': 'modeling_realm',
I think we actually don't use realm in nchelpers, I'll remove it.

2021-08-06 20:08 UTC, corviday commented on nchelpers/__init__.py
> +                'project': 'project_id',
My thinking on this was twofold.

1) First, based on the sample values they gave for `activity_id`, I wasn't sure they were synonymous with our usage of `project_id`. They suggest "CMIP" as apossible value for `activity_id`but not a specific CMIP version as possible values. However, nchelpers needs a way to know what specific CMIP version a dataset adheres to.

2) Currently, nchelpers is hardwired to look for an attribute called `project_id` - as the value of that attribute that is used to determine which of these dictionaries to use.

2021-08-06 20:52 UTC, corviday commented on nchelpers/__init__.py
> +                'project': 'project_id',
After discussion, we have decided to switch from a single attribute to determine which (if any) version of CMIP a file is to a heuristic function

2021-09-10 16:32 UTC, rod-glover commented on nchelpers/__init__.py
> +        def __get_metadata_standard__(self):
Eh, tiny comment here: I think "dunder" identifiers are (mainly) for magic methods like `__str__`, `__eq__`, etc. that the language uses to implement built-in functions and operators such as `str()`, `==`, etc. So maybe this should just be  `_get_metadata_standard`?

2021-09-10 16:33 UTC, rod-glover approved these changes
LGTM

2021-09-10 17:35 UTC, merged